- name: create odoo user
  user: name=odoo
- name: install git
  apt: pkg=git state=present
- name: checkout odoo from github
  git: repo=git://github.com/odoo/odoo.git dest=/usr/local/odoo accept_hostkey=yes
